version: '3.4'

services:
  aviomicroservice:
    image: aviomicroservice:dev
    container_name: AvioMicroservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "AvioMicroservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_aviomicroservice$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\AvioMicroservice:/app
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_aviomicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_aviomicroservice$ \"/src/../../PROJECT/MAANPP20/AvioMicroservice/bin/Debug/netcoreapp3.1/AvioMicroservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  carmicroservice:
    image: carmicroservice:dev
    container_name: CarMicroservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "CarMicroservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_carmicroservice$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\CarMicroservice:/app
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_carmicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_carmicroservice$ \"/src/../../PROJECT/MAANPP20/CarMicroservice/bin/Debug/netcoreapp3.1/CarMicroservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  hotelmicroservice:
    image: hotelmicroservice:dev
    container_name: HotelMicroservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "HotelMicroservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_hotelmicroservice$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\HotelMicroservice:/app
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_hotelmicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_hotelmicroservice$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  paymentmicroservice:
    image: paymentmicroservice:dev
    container_name: PaymentMicroservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "PaymentMicroservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_paymentmicroservice$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\PaymentMicroservice:/app
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_paymentmicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_paymentmicroservice$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  sagamachine:
    image: sagamachine:dev
    container_name: SagaMachine
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SagaMachine"
    #environment:
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sagamachine$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\SagaMachine:/app
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sagamachine$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sagamachine$ \"\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true

  usermicroservice:
    image: usermicroservice:dev
    container_name: UserMicroservice
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "UserMicroservice"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_usermicroservice$
    volumes:
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20\UserMicroservice:/app
      - C:\Users\andre\Desktop\DIPLOMSKI\MAANPP20:/src
      - C:\Users\andre\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_usermicroservice$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_usermicroservice$ \"/src/../../PROJECT/MAANPP20/UserMicroservice/bin/Debug/netcoreapp3.1/UserMicroservice.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
